# Generated by Django 4.1.7 on 2023-02-20 17:15

from django.db import migrations, models
import django.db.models.deletion

def create_data(apps, schema_editor):
    StockHolding = apps.get_model('stocks', 'StockHolding')
    Stock = apps.get_model('stocks', 'Stock')
    stock = Stock.objects.first()
    StockHolding(shares=1, purchasePrice=10, desiredPercentage=10, stock=stock).save()

class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0002_stocks"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockHolding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shares", models.PositiveIntegerField()),
                ("purchasePrice", models.DecimalField(decimal_places=2, max_digits=10)),
                ("desiredPercentage", models.DecimalField(decimal_places=1, max_digits=4)),
                ("stock", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="stocks.stock")),
            ],
        ),
        migrations.RunPython(create_data)
    ]
